// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations precisam de conexão direta (sem pgbouncer); o app em
  // runtime usa DATABASE_URL (pooled) via adapter em src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
